sudo: required
services:
  - docker

before_install:
  - docker image build -t zackhot/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker container run zackhot/react-test npm test -- --coverage

after_success:
  - docker image build -t zackhot/multi-client ./client
  - docker image build -t zackhot/multi-nginx ./nginx
  - docker image build -t zackhot/multi-server ./server
  - docker image build -t zackhot/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push zackhot/multi-client
  - docker push zackhot/multi-nginx
  - docker push zackhot/multi-server
  - docker push zackhot/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-581588823268
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY